### ISSUE TITLE
GHA: shinyjster-firefox tests failing on all Mac builds consistently

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#186]
Since Sep 20, all the apps are failing on all Mac builds (R3.4, 3.5, 3.6, 4.0, 4.1) consistently (with a [timeout](https://github.com/rstudio/shinycoreci-apps/runs/3729882494?check_suite_focus=true#step:32:4452)). This is because the shinyjster tests are specifically failing on firefox browser.

Sample log from https://pipelines.actions.githubusercontent.com/7D7nBlSdDrw0I67fqFPzdTKzjkyxAMv8ENWHMkl5rWao4xTGuf/_apis/pipelines/1/runs/3429/signedlogcontent/24?urlExpires=2021-09-29T00%3A55%3A22.8129672Z&urlSigningMethod=HMACV1&urlSignature=%2BApgZ7WBbEcaNlqDWZvjZImPlnR5Nie08oNIQ%2BdNr%2B0%3D

```
2021-09-28T12:17:09.0990950Z Loading required package: shiny
2021-09-28T12:17:09.1239560Z shinyjster - starting app: 134-async-hold-timers
2021-09-28T12:17:09.2435120Z 
2021-09-28T12:17:09.2436810Z Listening on http://127.0.0.1:48897
2021-09-28T12:17:09.7216080Z Running java -jar \
2021-09-28T12:17:09.7217080Z   /Users/runner/work/_temp/Library/shinyjster/selenium/selenium.jar firefox \
2021-09-28T12:17:09.7218530Z   1200x1200 'http://127.0.0.1:48897/?shinyjster=1' 120 -headless
2021-09-28T12:17:32.5008290Z pxjava - Exception in thread "main" java.lang.reflect.InvocationTargetException
2021-09-28T12:17:32.5010840Z pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-09-28T12:17:32.5013660Z pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-09-28T12:17:32.5016950Z pxjava - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-09-28T12:17:32.5019560Z pxjava - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2021-09-28T12:17:32.5021390Z pxjava - 	at com.rstudio.seleniumRunner.MainKt.main(Main.kt:73)
2021-09-28T12:17:32.5024170Z pxjava - Caused by: org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:2571
2021-09-28T12:17:32.5027030Z pxjava - Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
2021-09-28T12:17:32.5029710Z pxjava - System info: host: 'Mac-1632816324812.local', ip: '10.79.1.174', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_302'
2021-09-28T12:17:32.5031840Z pxjava - Driver info: driver.version: FirefoxDriver
2021-09-28T12:17:32.5034830Z pxjava - 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
2021-09-28T12:17:32.5037730Z pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
2021-09-28T12:17:32.5040340Z pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
2021-09-28T12:17:32.5042800Z pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
2021-09-28T12:17:32.5044980Z pxjava - 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
2021-09-28T12:17:32.5046340Z pxjava - 	... 5 more
2021-09-28T12:17:32.5047720Z pxjava - Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:2571
2021-09-28T12:17:32.5049910Z pxjava - 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
2021-09-28T12:17:32.5052460Z pxjava - 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
2021-09-28T12:17:32.5055560Z pxjava - 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2021-09-28T12:17:32.5058640Z pxjava - 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2021-09-28T12:17:32.5061680Z pxjava - 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2021-09-28T12:17:32.5064410Z pxjava - 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2021-09-28T12:17:32.5067080Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-28T12:17:32.5069660Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-09-28T12:17:32.5072130Z pxjava - 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2021-09-28T12:17:32.5074640Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-28T12:17:32.5077930Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-09-28T12:17:32.5080580Z pxjava - 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2021-09-28T12:17:32.5083570Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-28T12:17:32.5088400Z pxjava - 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2021-09-28T12:17:32.5092430Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-28T12:17:32.5095050Z pxjava - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-09-28T12:17:32.5097470Z pxjava - 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2021-09-28T12:17:32.5099260Z pxjava - 	at okhttp3.RealCall.execute(RealCall.java:77)
2021-09-28T12:17:32.5101330Z pxjava - 	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
2021-09-28T12:17:32.5104120Z pxjava - 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
2021-09-28T12:17:32.5108420Z pxjava - 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
2021-09-28T12:17:32.5111370Z pxjava - 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
2021-09-28T12:17:32.5114450Z pxjava - 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
2021-09-28T12:17:32.5116390Z pxjava - 	... 9 more
2021-09-28T12:17:32.5117760Z pxjava - Caused by: java.net.ConnectException: Connection refused (Connection refused)
2021-09-28T12:17:32.5119470Z pxjava - 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2021-09-28T12:17:32.5121550Z pxjava - 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2021-09-28T12:17:32.5124070Z pxjava - 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2021-09-28T12:17:32.5126530Z pxjava - 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2021-09-28T12:17:32.5128510Z pxjava - 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2021-09-28T12:17:32.5130010Z pxjava - 	at java.net.Socket.connect(Socket.java:607)
2021-09-28T12:17:32.5131790Z pxjava - 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
2021-09-28T12:17:32.5134510Z pxjava - 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
2021-09-28T12:17:32.5136160Z pxjava - 	... 31 more
2021-09-28T12:17:32.5137080Z pxjava - Selenium Processx closed
```

<img width="1630" alt="Mac_builds_failing_shinyjster_firefox_tests" src="https://user-images.githubusercontent.com/5369655/135186318-d51a3e4c-8652-4e4c-8f7a-a460dae86ba0.png">

**Comment by MadhulikaTanuboddi** [comment]
Temporarily fixed by https://github.com/rstudio/shinycoreci-apps/issues/186
