### ISSUE TITLE
Github Actions: Windows test results not displayed on few R versions due to time out

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#96]
Working: 
Windows 4.0: https://github.com/rstudio/shinycoreci-apps/runs/1548870973?check_suite_focus=true#step:30:30445
Windows 3.4: https://github.com/rstudio/shinycoreci-apps/runs/1548871149?check_suite_focus=true#step:30:28377 

Not Working:
Windows 3.6: https://github.com/rstudio/shinycoreci-apps/runs/1548871046?check_suite_focus=true#step:30:19242
Windows 3.5: https://github.com/rstudio/shinycoreci-apps/runs/1548871104?check_suite_focus=true#step:30:19111

<img width="1664" alt="GHA_Windows_run" src="https://user-images.githubusercontent.com/5369655/102156750-0c90c300-3e33-11eb-96ed-3818652621bd.png">

**Comment by cpsievert** [comment]
This is probably fixed now

**Comment by MadhulikaTanuboddi** [comment]
Following upon this.

The Windows builds ran well during Feb and almost until mid march. But, I have been noticing time outs again only on Windows build since mid march. This is happening on only Windows build (all R versions). 

For ex: from April 5 review, all Windows builds are timing out

R4.0: https://github.com/rstudio/shinycoreci-apps/runs/2268362344?check_suite_focus=true#step:31:27003
R3.6: https://github.com/rstudio/shinycoreci-apps/runs/2268362461?check_suite_focus=true#step:31:27053
R3.5: https://github.com/rstudio/shinycoreci-apps/runs/2268362516?check_suite_focus=true#step:31:207
R3.4: https://github.com/rstudio/shinycoreci-apps/runs/2268362563?check_suite_focus=true#step:31:23920

**Comment by MadhulikaTanuboddi** [comment]
Closing this issue as these timeouts are happening due to a different issue. more details at https://github.com/rstudio/shinycoreci-apps/issues/133

**Comment by MadhulikaTanuboddi** [comment]
I noticed that Windows builds timeouts started happening again. However, its not consistently happening with all the R versions. For ex: Check the "runTests" results from https://github.com/rstudio/shinycoreci-apps/actions/runs/775896165.

While Windows - 4.0, 3.5 and 3.4 looks good, Windows 3.6 run times out -> https://github.com/rstudio/shinycoreci-apps/runs/2415030210?check_suite_focus=true#step:31:137

Brief log:

```
pxjava - Exception in thread "main" java.lang.reflect.InvocationTargetException

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

pxjava - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

pxjava - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

pxjava - 	at com.rstudio.seleniumRunner.MainKt.main(Main.kt:73)

pxjava - Caused by: org.openqa.selenium.TimeoutException: No connection could be made because the target machine actively refused it. (os error 10061)

pxjava - Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
```

Similarly,  in https://github.com/rstudio/shinycoreci-apps/actions/runs/788354935

I noticed Windows (4.0, 3.6, 3.5) builds are timing out . 3.4 is ok.

**Comment by MadhulikaTanuboddi** [comment]
After chatting with Barret/Shalu, we noticed that the timeouts are happening during the Firefox run with the 001-hello app. Check the logs from https://github.com/rstudio/shinycoreci-apps/runs/2415030210?check_suite_focus=true#step:31:111

```
[3/368; 1m; 2h] 001-hello ~ shinyjster-firefox.R
Loading required package: shiny

shinyjster - starting app: 001-hello



Listening on http://127.0.0.1:36192

Running java -jar "D:/a/_temp/Library/shinyjster/selenium/selenium.jar" \

  firefox 1200x1200 "http://127.0.0.1:36192/?shinyjster=1" 120 -headless

pxjava - 1619133858881	geckodriver	INFO	Listening on 127.0.0.1:46326

pxjava - 1619133859594	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rust_mozprofileJRv1RX"

pxjava - Exception in thread "main" java.lang.reflect.InvocationTargetException

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

pxjava - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

pxjava - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

pxjava - 	at com.rstudio.seleniumRunner.MainKt.main(Main.kt:73)

pxjava - Caused by: org.openqa.selenium.TimeoutException: No connection could be made because the target machine actively refused it. (os error 10061)

pxjava - Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

pxjava - System info: host: 'fv-az177-783', ip: '10.1.0.48', os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'

pxjava - Driver info: driver.version: FirefoxDriver

pxjava - remote stacktrace: 

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

pxjava - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

pxjava - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

pxjava - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

pxjava - 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)

pxjava - 	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)

pxjava - 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)

pxjava - 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

pxjava - 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)

pxjava - 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)

pxjava - 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)

pxjava - 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)

pxjava - 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)

pxjava - 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)

pxjava - 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

pxjava - 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)

pxjava - 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)

pxjava - 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)

pxjava - 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)

pxjava - 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)

pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)

pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)

pxjava - 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)

pxjava - 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)

pxjava - 	... 5 more

pxjava - Selenium Processx closed


Execution halted
Error: The action has timed out.
```

**Comment by MadhulikaTanuboddi** [comment]
May 4: Windows 4.0 run timeout - https://github.com/rstudio/shinycoreci-apps/runs/2498695531?check_suite_focus=true#step:31:24419
